### ISSUE TITLE
Jumping/ movement to avoid taunt

### ISSUE THREAD

**Issue by 4HueZee** [fletchette/dez#4]
Players who jump or weapon switch at the exact time of the spycrab will be able to avoid the taunt. by putting crabsonly brush ontop of crabhammer the weapons switching issue is gone. however during stage one and stage 2 crab showdown. players may jump to avoid crabbing. 

to fix players need to be stuck in place. during both stages.

weapon switching may be solved by using crabsonly inside the stage 2 zone.

you may choose whether or not to integrate it to the single script. but please make a note of it if you do.

**Comment by fletchette** [comment]
@Dezmun-d can you add the crabsOnly onto the wincrabHammer1 and wincrabHammer2 area please
